package com.tiagohs.entities.enums

enum class MovieInfoType {
    INFO_HEADER,
    INFO_SUMMARY,
    INFO_CAST,
    INFO_CREW,
    INFO_REVIEWS,
    INFO_DIRECTORS_MOVIE,
    INFO_COLLECTION,
    INFO_PRODUCTION,
    INFO_MIDIAS,
    INFO_QUOTE,
    INFO_BLOCK_SPECIAL,
    INFO_WATCH_ON,
    INFO_DID_YOUT_KNOW;
}