apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

android {
    def globalConfiguration = rootProject.extensions.getByName("ext")

    compileSdkVersion globalConfiguration["compileSDK"]

    defaultConfig {
        minSdkVersion globalConfiguration["minSDK"]
        targetSdkVersion globalConfiguration["targetSDK"]


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    namespace 'com.tiagohs.helpers'
}

dependencies {
    implementation project(path: ':entities')

    def dependencies = rootProject.ext.dependencies

    implementation platform(dependencies.firebaseBom)

    
    // Android Core / Material
    implementation dependencies.appcompat
    implementation dependencies.androidxCore
    implementation dependencies.constrantlayout
    implementation dependencies.browser
    implementation dependencies.androidMaterial
    implementation dependencies.imageViewer
    implementation dependencies.overflowPager

    // Tools
    implementation dependencies.timber

    // Rx
    implementation dependencies.rxAndroid
    implementation dependencies.rxJava
    implementation dependencies.rxPreferences

    // Retrofit
    implementation dependencies.retrofit2
    implementation dependencies.retrofit2JacksonConverter
    implementation dependencies.retrofit2GsonConverter
    implementation dependencies.retrofit2RxJavaAdapter

    // Okhttp3
    implementation dependencies.okhttp3
    implementation dependencies.okhttp3LoggingInterceptor

    // Glide

    // Glide
    implementation dependencies.glide
    implementation dependencies.glide_transformations
    kapt dependencies.glideCompiler

    // Firebase
    implementation dependencies.firebaseStorage
    implementation dependencies.firebaseUiStorage

    // Test Tools
    testImplementation dependencies.junit
    androidTestImplementation dependencies.testRunner
    androidTestImplementation dependencies.espresso
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}
